alias source='source ~/.zshrc'
alias catalias='cat ~/.oh-my-zsh/custom/aliases.zsh'

alias aws_bash='aws-vault exec loadtest -- bash -l'
alias al_bash='aws-vault exec loadtest -- bash -l'

alias gp='git pull'
alias gs='git status'
alias gaa='git add .'
alias gc='git checkout'
alias gcb=' git checkout -b'
alias gcm='git commit'
alias gb='git branch'
alias gri='git rebase -i'
alias gr='git rebase'
alias gsa='git stash apply'
alias gl='git log --all --decorate --oneline --graph'

alias dpa='docker ps -a'
alias killdock='docker kill $(docker ps -q); docker rm $(docker ps -a -q)'
alias dsp='docker system prune'
alias dpf='docker volume prune -f'

alias home='cd ~'
alias c='clear'
alias cdujet='cd /Users/brian/Ujet'
alias qa-base='cd ~/Ujet/qa-base'
alias lccs='cd ~/Ujet/qa-lccs'
alias webpo='cd ~/Ujet/qa-web-po'
alias admin-portal='cd ~/Ujet/qa-admin-portal-tests'
alias android='cd ~/Ujet/qa-mobile-tests'
alias lgp='export LOCAL_GEM_PATH=/Users/brianyip/UJET'
